"""'Added ban table'

Revision ID: 85a3f8dcbae5
Revises: 1abdbdd30654
Create Date: 2025-04-15 12:08:02.804539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85a3f8dcbae5'
down_revision: Union[str, None] = '1abdbdd30654'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
