version: "3.9"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: AsyncUserDb
      POSTGRES_PASSWORD: somepassw189309
      POSTGRES_DB: AsyncFastApi
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  main_app:
    build: .
    depends_on:
      - db
    expose:
      - "8000"
    volumes:
      - .:/app
    command: ["python", "-m", "app.main"]

  admin:
    build: .
    depends_on:
      - db
    expose:
      - "8080"
    volumes:
      - .:/app
    command: ["python", "panel.py"]

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro 
    depends_on:
      - main_app
      - admin

  alembic:
    build: .
    depends_on:
      - db
    volumes:
      - .:/app
    command: ["alembic", "upgrade", "head"]

volumes:
  pg_data: